env:
  browser: true
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-console: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - warn
    - never
  comma-dangle:
    - warn
    - arrays: ignore
      objects: ignore
      imports: never
      exports: never
      functions: ignore
  no-var: warn
  object-shorthand: warn
  prefer-arrow-callback: warn
  prefer-spread: warn
  arrow-parens: ["warn", "as-needed"]
  arrow-body-style: ["warn", "as-needed"]
  prefer-const: warn
